/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class Poller
 *
 * This file has been generated by dub 2.2.0.
 */
#include "dub/dub.h"
#include "lens/Poller.h"

using namespace lens;

/** lens::Poller::Poller(int reserve=8)
 * include/lens/Poller.h:137
 */
static int Poller_Poller(lua_State *L) {
  try {
    int top__ = lua_gettop(L);
    if (top__ >= 1) {
      int reserve = dub::checkint(L, 1);
      Poller *retval__ = new Poller(reserve);
      retval__->dub_pushobject(L, retval__, "lens.Poller", true);
      return 1;
    } else {
      Poller *retval__ = new Poller();
      retval__->dub_pushobject(L, retval__, "lens.Poller", true);
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "new: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "new: Unknown exception");
  }
  return dub::error(L);
}

/** lens::Poller::~Poller()
 * include/lens/Poller.h:139
 */
static int Poller__Poller(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub::checksdata_d(L, 1, "lens.Poller"));
    if (userdata->gc) {
      Poller *self = (Poller *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "__gc: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "__gc: Unknown exception");
  }
  return dub::error(L);
}

/** bool lens::Poller::poll(double wake_at)
 * include/lens/Poller.h:149
 */
static int Poller_poll(lua_State *L) {
  try {
    Poller *self = *((Poller **)dub::checksdata(L, 1, "lens.Poller"));
    double wake_at = dub::checknumber(L, 2);
    lua_pushboolean(L, self->poll(wake_at));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "poll: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "poll: Unknown exception");
  }
  return dub::error(L);
}

/** void lens::Poller::runGUI(double wake_at)
 * include/lens/Poller.h:210
 */
static int Poller_runGUI(lua_State *L) {
  try {
    Poller *self = *((Poller **)dub::checksdata(L, 1, "lens.Poller"));
    double wake_at = dub::checknumber(L, 2);
    self->runGUI(wake_at);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "runGUI: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "runGUI: Unknown exception");
  }
  return dub::error(L);
}

/** LuaStackSize lens::Poller::events(lua_State *L)
 * include/lens/Poller.h:245
 */
static int Poller_events(lua_State *L) {
  try {
    Poller *self = *((Poller **)dub::checksdata(L, 1, "lens.Poller"));
    return self->events(L);
  } catch (std::exception &e) {
    lua_pushfstring(L, "events: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "events: Unknown exception");
  }
  return dub::error(L);
}

/** int lens::Poller::fflags(int idx)
 * include/lens/Poller.h:274
 */
static int Poller_fflags(lua_State *L) {
  try {
    Poller *self = *((Poller **)dub::checksdata(L, 1, "lens.Poller"));
    int idx = dub::checkint(L, 2);
    lua_pushnumber(L, self->fflags(idx));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "fflags: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "fflags: Unknown exception");
  }
  return dub::error(L);
}

/** int lens::Poller::add(int fd, int filter, int fflags=0)
 * include/lens/Poller.h:323
 */
static int Poller_add(lua_State *L) {
  try {
    Poller *self = *((Poller **)dub::checksdata(L, 1, "lens.Poller"));
    int top__ = lua_gettop(L);
    if (top__ >= 4) {
      int fd = dub::checkint(L, 2);
      int filter = dub::checkint(L, 3);
      int fflags = dub::checkint(L, 4);
      lua_pushnumber(L, self->add(fd, filter, fflags));
      return 1;
    } else {
      int fd = dub::checkint(L, 2);
      int filter = dub::checkint(L, 3);
      lua_pushnumber(L, self->add(fd, filter));
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "add: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "add: Unknown exception");
  }
  return dub::error(L);
}

/** void lens::Poller::modify(int idx, int filter, lua_State *L)
 * include/lens/Poller.h:330
 */
static int Poller_modify(lua_State *L) {
  try {
    Poller *self = *((Poller **)dub::checksdata(L, 1, "lens.Poller"));
    int idx = dub::checkint(L, 2);
    int filter = dub::checkint(L, 3);
    self->modify(idx, filter, L);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "modify: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "modify: Unknown exception");
  }
  return dub::error(L);
}

/** void lens::Poller::remove(int idx)
 * include/lens/Poller.h:387
 */
static int Poller_remove(lua_State *L) {
  try {
    Poller *self = *((Poller **)dub::checksdata(L, 1, "lens.Poller"));
    int idx = dub::checkint(L, 2);
    self->remove(idx);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "remove: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "remove: Unknown exception");
  }
  return dub::error(L);
}

/** int lens::Poller::count()
 * include/lens/Poller.h:420
 */
static int Poller_count(lua_State *L) {
  try {
    Poller *self = *((Poller **)dub::checksdata(L, 1, "lens.Poller"));
    lua_pushnumber(L, self->count());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "count: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "count: Unknown exception");
  }
  return dub::error(L);
}

/** LuaStackSize lens::Poller::idxToPos(int idx, lua_State *L)
 * include/lens/Poller.h:427
 */
static int Poller_idxToPos(lua_State *L) {
  try {
    Poller *self = *((Poller **)dub::checksdata(L, 1, "lens.Poller"));
    int idx = dub::checkint(L, 2);
    return self->idxToPos(idx, L);
  } catch (std::exception &e) {
    lua_pushfstring(L, "idxToPos: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "idxToPos: Unknown exception");
  }
  return dub::error(L);
}

/** LuaStackSize lens::Poller::posToIdx(int pos, lua_State *L)
 * include/lens/Poller.h:436
 */
static int Poller_posToIdx(lua_State *L) {
  try {
    Poller *self = *((Poller **)dub::checksdata(L, 1, "lens.Poller"));
    int pos = dub::checkint(L, 2);
    return self->posToIdx(pos, L);
  } catch (std::exception &e) {
    lua_pushfstring(L, "posToIdx: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "posToIdx: Unknown exception");
  }
  return dub::error(L);
}

/** LuaStackSize lens::Poller::posToFd(int pos, lua_State *L)
 * include/lens/Poller.h:445
 */
static int Poller_posToFd(lua_State *L) {
  try {
    Poller *self = *((Poller **)dub::checksdata(L, 1, "lens.Poller"));
    int pos = dub::checkint(L, 2);
    return self->posToFd(pos, L);
  } catch (std::exception &e) {
    lua_pushfstring(L, "posToFd: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "posToFd: Unknown exception");
  }
  return dub::error(L);
}

/** LuaStackSize lens::Poller::posToEvent(int pos, lua_State *L)
 * include/lens/Poller.h:458
 */
static int Poller_posToEvent(lua_State *L) {
  try {
    Poller *self = *((Poller **)dub::checksdata(L, 1, "lens.Poller"));
    int pos = dub::checkint(L, 2);
    return self->posToEvent(pos, L);
  } catch (std::exception &e) {
    lua_pushfstring(L, "posToEvent: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "posToEvent: Unknown exception");
  }
  return dub::error(L);
}

/** static LuaStackSize lens::Poller::eventMap(int fflags, lua_State *L)
 * include/lens/Poller.h:285
 */
static int Poller_eventMap(lua_State *L) {
  try {
    int fflags = dub::checkint(L, 1);
    return Poller::eventMap(fflags, L);
  } catch (std::exception &e) {
    lua_pushfstring(L, "eventMap: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "eventMap: Unknown exception");
  }
  return dub::error(L);
}



// --=============================================== __tostring
static int Poller___tostring(lua_State *L) {
  Poller *self = *((Poller **)dub::checksdata_n(L, 1, "lens.Poller"));
  lua_pushfstring(L, "lens.Poller: %p (%f)", self, self-> count());
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg Poller_member_methods[] = {
  { "new"          , Poller_Poller        },
  { "__gc"         , Poller__Poller       },
  { "poll"         , Poller_poll          },
  { "runGUI"       , Poller_runGUI        },
  { "events"       , Poller_events        },
  { "fflags"       , Poller_fflags        },
  { "add"          , Poller_add           },
  { "modify"       , Poller_modify        },
  { "remove"       , Poller_remove        },
  { "count"        , Poller_count         },
  { "idxToPos"     , Poller_idxToPos      },
  { "posToIdx"     , Poller_posToIdx      },
  { "posToFd"      , Poller_posToFd       },
  { "posToEvent"   , Poller_posToEvent    },
  { "eventMap"     , Poller_eventMap      },
  { "__tostring"   , Poller___tostring    },
  { "deleted"      , dub::isDeleted       },
  { NULL, NULL},
};

// --=============================================== CONSTANTS
static const struct dub::const_Reg Poller_const[] = {
  { "Read"         , Poller::Read         },
  { "Write"        , Poller::Write        },
  { "VNode"        , Poller::VNode        },
  { NULL, 0},
};

extern "C" int luaopen_lens_Poller(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "lens.Poller");
  // <mt>
  // register class constants
  dub::register_const(L, Poller_const);

  // register member methods
  dub::fregister(L, Poller_member_methods);
  // setup meta-table
  dub::setup(L, "lens.Poller");
  // <mt>
  return 1;
}
